return {

    [0x0001] = "error_depercated",                                
    [0x0002] = "error_bad_arg",
    [0x0003] = "error_tried_to_run_studio_only_code",
    [0x0004] = "error_no_entry",

    ["explanations"] = {
        [0x0001] = "attempted to execute a depercated function...",
        [0x0002] = "a bad argument was passed...",
        [0x0003] = "attempted to run a studio only code block...",
        [0x0004] = "did you forget to implement 'entry'?"
    },
}
